name: "Examples"

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    paths-ignore:
      - '*.gif'
      - '*.png'
      - '*.yml'
      - '*.md'
      - 'LICENSE'

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        version:
          - mini
    steps:
      - name: "Cancel similar actions in progress"
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Install Nim
        run: |
          wget -qO - https://nim-lang.org/choosenim/init.sh | bash -s -- -y
          echo "$HOME/.nimble/bin" >> $GITHUB_PATH

      - name: Verify dependecies
        run: |
          nim --version

      - name: Build Arturo
        run: |
          ./install ${{ matrix.version }} log
          echo "$HOME/.arturo/bin" >> $GITHUB_PATH

      - name: Run examples/projecteuler
        run: |
          (
            cd examples/projecteuler
            for artfile in ./euler*.art; do
              echo "== $artfile =="
              arturo "$artfile"
            done
          )

      - name: Run examples/rosetta
        run: |
          (
            cd examples/rosetta
            for artfile in ./*.art; do
              echo "== $artfile =="
              arturo "$artfile"
            done
          )
